apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - secret.yaml

images:
  - name: db-image
    newName: postgres
    newTag: "16"

patches:
  - path: statefulset.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: postgres