apiVersion: v1
kind: ConfigMap
metadata:
  name: slack-metrics-config
  namespace: app
  labels:
    app: slack-metrics
data:
  GOCONF: "/app/config/config.toml.tmpl"
  LOG_LEVEL: "info"
  API_ENABLE_LOG_EXCLUSION: "true"
  SES_USE_MOCK: "false"
  SES_FROM_EMAIL: "noreply@stg.cloud-pratica.com"
  POSTGRES_MAIN_SSL_MODE: "require"
  SLACK_USE_MOCK: "false"
  SQS_USE_MOCK: "false"
  SQS_PRODUCED_QUEUE_URL_SELF: "https://sqs.ap-northeast-1.amazonaws.com/422752180329/slack-metrics-stg"
  SQS_CONSUMED_QUEUE_URL: "https://sqs.ap-northeast-1.amazonaws.com/422752180329/slack-metrics-stg"
  API_CORS_ALLOWED_ORIGINS: "https://sm.stg.cloud-pratica.com"
