apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-metrics-external-secret
  namespace: app
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cp-css
    kind: ClusterSecretStore
  target:
    name: slack-metrics-secret
    creationPolicy: Owner
  data:
    - secretKey: db_host
      remoteRef:
        key: db-main-instance-stg
        property: host
    - secretKey: db_user
      remoteRef:
        key: db-main-instance-stg
        property: slack_metrics_user
    - secretKey: db_password
      remoteRef:
        key: db-main-instance-stg
        property: slack_metrics_password
