apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
- service-account.yaml
- deployment.yaml
- cronjob-sync-user.yaml
- cronjob-sync-workspaces.yaml
- service.yaml