apiVersion: v1
kind: Service
metadata:
  name: slack-metrics-service
  namespace: app
  labels:
    app: slack-metrics
spec:
  type: ClusterIP
  selector:
    app: slack-metrics
  ports:
    - name: http
      port: 80 # Service port
      targetPort: 8080 # Container port
      protocol: TCP