apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cp-css
  namespace: external-secrets
spec:
  provider:
    aws:
      region: ap-northeast-1
      service: SecretsManager