apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cp-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: slack-metrics.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: slack-metrics-service
                port:
                  number: 80