apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: app-image
    newName: 043309350350.dkr.ecr.ap-northeast-1.amazonaws.com/db-migrator-stg
    newTag: b9b12c6

patches:
  - path: job.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: db-migrator-job