apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cp-ingress
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: cp-k8s-stg
    # *.stg.sample-app.click のhttps証明書
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-1:422752180329:certificate/fe5a6a72-117a-4da5-af05-2c66301c1be2
spec:
  rules:
    - host: sm-api-v2.stg.sample-app.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: slack-metrics-service
                port:
                  number: 80