apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-metrics-deployment
  namespace: app
spec:
  selector:
    matchLabels:
      app: slack-metrics
  template:
    metadata:
      labels:
        app: slack-metrics
    spec:
      serviceAccountName: slack-metrics-sa
      containers:
        - name: slack-metrics
          image: app-image
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: slack-metrics-config
          env:
            - name: MODE
              value: "api"
            - name: POSTGRES_MAIN_HOST
              valueFrom:
                secretKeyRef:
                  name: slack-metrics-secret
                  key: db_host
            - name: POSTGRES_MAIN_USER
              valueFrom:
                secretKeyRef:
                  name: slack-metrics-secret
                  key: db_user
            - name: POSTGRES_MAIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: slack-metrics-secret
                  key: db_password
          livenessProbe: # コンテナが生きているかどうかを確認
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe: # リクエストを受け付けるかどうかを確認
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
