apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - external-secret.yaml

images:
  - name: app-image
    newName: 422752180329.dkr.ecr.ap-northeast-1.amazonaws.com/db-migrator-stg
    newTag: 53aae3e # GitHub Actionsのフローで書き換える

patches:
  - path: job.yaml
    target:
      kind: Job
      name: db-migrator-job