apiVersion: v1
kind: Service
metadata:
  name: slack-metrics-service-nodeport
  labels:
    app: slack-metrics
spec:
  type: NodePort
  selector:
    app: slack-metrics
  ports:
    - name: http
      port: 80 # Service port
      targetPort: 8080 # Container port
      nodePort: 30000 # Node port
      protocol: TCP