apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
- ../../base
- configmap.yaml
- hpa.yaml
- external-secret.yaml

images:
- name: app-image
  newName: 422752180329.dkr.ecr.ap-northeast-1.amazonaws.com/slack-metrics-stg
  newTag: 46b4430

patches:
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: slack-metrics-deployment
  - path: deployment-worker.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: slack-metrics-worker-deployment
  - path: cronjob-sync-workspaces.yaml
    target:
      group: batch
      version: v1
      kind: CronJob
      name: sync-workspaces-cj
  - path: cronjob-sync-user.yaml
    target:
      group: batch
      version: v1
      kind: CronJob
      name: sync-users-cj
